import type { Lang } from "@/i18n/lang";

export const faqItems: Record<Lang, Array<{ q: string; a: string }>> = {
  es: [
    { q: "¿Qué es Playas on Tech?", a: "Playas on Tech es la comunidad de tecnología de Manzanillo, Colima. Reúne a desarrolladores, diseñadores, founders y entusiastas de la tecnología en meetups gratuitos que se realizan cada dos meses, frente al mar. Desde julio de 2025 hemos celebrado seis ediciones, con más de 200 asistentes acumulados." },
    { q: "¿Dónde se realiza Playas on Tech?", a: "Los meetups se realizan en Manzanillo, Colima, México — en venues de la zona hotelera, siempre cerca o frente al mar. La 7ª edición (julio 2026) será en el Hotel Marbella, sobre Playa Azul Salagua." },
    { q: "¿Cuándo es el próximo evento?", a: "El próximo meetup es nuestro 7º aniversario: sábado 18 de julio de 2026, de 10:00 a 18:00 hrs, en el Hotel Marbella, Manzanillo. Después de esa fecha, mantenemos cadencia bimestral." },
    { q: "¿Cuánto cuesta asistir?", a: "La asistencia a Playas on Tech es 100% gratuita. No cobramos entrada, registro ni materiales — nos sostenemos con donaciones de la comunidad y patrocinios." },
    { q: "¿Quién puede asistir? ¿Necesito experiencia en tecnología?", a: "Cualquier persona interesada en tecnología puede asistir. No se requiere experiencia previa: recibimos desarrolladores senior, estudiantes, diseñadores, founders y curiosos. Si quieres aprender o conocer a la comunidad tech de la costa, aquí cabes." },
    { q: "¿Cómo me registro?", a: "El registro se hace en playasontech.com, en la sección del próximo evento. Para el 7º aniversario, el registro se gestiona vía Eventbrite con una cuota de recuperación de $350 MXN, y el cupo es limitado." },
    { q: "¿Qué tipo de charlas se dan?", a: "Cubrimos temas amplios de tecnología: desarrollo web, animación con GSAP, IA y autenticación, open source, comunidad y código. Hay charlas técnicas profundas, lightning talks y paneles. Las grabaciones quedan en nuestro canal de YouTube @PlayasOnTech." },
    { q: "¿Cómo propongo una charla?", a: "Cualquier persona puede proponer una charla a través de nuestro formulario público — el enlace está en la sección «Sé voluntario» y en el footer. Revisamos las propuestas en orden y respondemos antes del cierre de programa de cada edición." },
    { q: "¿Quién organiza Playas on Tech?", a: "Playas on Tech es organizada por un equipo de voluntarios en su tiempo libre, sin fines de lucro. El equipo actual: Danny, Franky, H, Juaneque, Kev y Mane. Buscamos siempre manos nuevas para sumar al equipo." },
    { q: "¿Hay comunidades tech similares en Manzanillo o Colima?", a: "Playas on Tech es la comunidad de tecnología activa más grande en la costa de Colima, con cadencia bimestral y entrada gratuita. Si conoces otra iniciativa tech local que quiera colaborar, escríbenos." },
    { q: "¿Cómo apoyo a la comunidad?", a: "Puedes apoyar de tres formas: (1) donando vía PayPal o Patreon — los enlaces están en la sección Donaciones; (2) patrocinando una edición o el aniversario, con paquetes desde $5,000 MXN; (3) sumándote como voluntario al equipo organizador." },
    { q: "¿Hay grabaciones de los eventos pasados?", a: "Sí. Todas las sesiones recientes están en nuestro canal de YouTube — @PlayasOnTech — bajo licencia Creative Commons (CC BY 4.0). Las puedes ver, compartir y reutilizar dando crédito." },
  ],
  en: [
    { q: "What is Playas on Tech?", a: "Playas on Tech is Manzanillo's tech community in Colima, Mexico. It gathers developers, designers, founders, and tech enthusiasts in free meetups held every two months, by the sea. Since July 2025, we have held six editions with over 200 cumulative attendees." },
    { q: "Where is Playas on Tech held?", a: "The meetups are held in Manzanillo, Colima, Mexico — at venues in the hotel zone, always near or by the sea. The 7th edition (July 2026) will take place at Hotel Marbella, on Playa Azul Salagua." },
    { q: "When is the next event?", a: "The next meetup is our 7th anniversary: Saturday, July 18, 2026, from 10:00 AM to 6:00 PM, at Hotel Marbella, Manzanillo. After that date, we will maintain our bi-monthly cadence." },
    { q: "How much does it cost to attend?", a: "Attending Playas on Tech is 100% free. We do not charge for entry, registration, or materials — we support ourselves through community donations and sponsorships." },
    { q: "Who can attend? Do I need tech experience?", a: "Anyone interested in technology can attend. No prior experience is required: we welcome senior developers, students, designers, founders, and the curious. If you want to learn or meet the coast's tech community, you belong here." },
    { q: "How do I register?", a: "Registration is done on playasontech.com, in the next event section. For the 7th anniversary, registration is managed via Eventbrite with a $350 MXN recovery fee, and space is limited." },
    { q: "What kind of talks are given?", a: "We cover broad tech topics: web development, GSAP animation, AI and authentication, open source, community, and coding. There are deep technical talks, lightning talks, and panels. Recordings are uploaded to our YouTube channel @PlayasOnTech." },
    { q: "How do I propose a talk?", a: "Anyone can propose a talk through our public form — the link is in the 'Volunteer' section and in the footer. We review submissions in order and reply before each edition's program closes." },
    { q: "Who organizes Playas on Tech?", a: "Playas on Tech is organized by a team of volunteers in their free time, on a non-profit basis. The current team: Danny, Franky, H, Juaneque, Kev, and Mane. We are always looking for new hands to join the team." },
    { q: "Are there similar tech communities in Manzanillo or Colima?", a: "Playas on Tech is the largest active tech community on the Colima coast, with a bi-monthly cadence and free admission. If you know of another local tech initiative that would like to collaborate, write to us." },
    { q: "How do I support the community?", a: "You can support us in three ways: (1) donating via PayPal or Patreon — the links are in the Donations section; (2) sponsoring an edition or the anniversary, with packages starting at $5,000 MXN; (3) joining the organizing team as a volunteer." },
    { q: "Are there recordings of past events?", a: "Yes. All recent sessions are on our YouTube channel — @PlayasOnTech — under the Creative Commons license (CC BY 4.0). You can watch, share, and reuse them with attribution." },
  ],
};
